### PR TITLE
Fix broken mathjax in Discourse 1.5.0

### PR DESCRIPTION
**Pull request by masda70**
1.5.0 has changed wmd-preview into d-editor-preview. As to semantic versioning, perhaps this should a 0.5.0 instead.

I removed the "caretPosition" update, not sure what it does (or if it's useful).

Mathjax code is also more robust to initialization (for example the old version was broken if a page was refreshed while the preview was holding a draft post).

### CODE REVIEW

**Comment by bruth** [comment]
Any chance this can be reviewed and merged?

**Comment by ntadej** [comment]
@masda70 Is this branch fit to be used in production? I want to update our Discourse instance and this plugin seems to be blocking it.

**Comment by kasperpeulen** [comment]
Can I merge this?

**Comment by Blaisorblade** [comment]
Hi!
@masda70 I also worked on bug #31 (there was no link to this PR); my (working) attempt is in #32.

I'm no JavaScript expert, but IIUC my branch has two interesting differences (which might be better):
- it actually uses the documented API `decorateCooked` as intended. Neither `.d-editor-preview` nor "topic" are part of the documented API; the callback can just transform its argument.
- it tries to be compatible with the old API using the compatibility link.

- My PR also uses $html[0] without checking for `length`, which I'm fixing right now.

> I removed the "caretPosition" update, not sure what it does (or if it's useful).

I ended up doing the same, Discourse seems to implement that already (as it should).

**Comment by Blaisorblade** [comment]
Additionally, during my testing it seemed that your approach would not work well, as `decorateCooked`'s callback is sometimes called before its argument is inserted in the page tree. (But maybe I was doing some other mistake at that point). Note I only tested with Discourse 1.5.1.

**Comment by Blaisorblade** [comment]
@masda70 I assume you've seen #32. I'd guess you'd need to merge `master` into your branch to solve the merge conflicts GitHub still reports. Or to open a new PR with the new changes so that it's easier to review?

**Comment by masda70** [comment]
Hey ! Thanks for your great work. There have been great enhancements in the plugin API making a lot of things irrelevant,  and this pull request is no longer relevant, I will close it.

**Comment by Blaisorblade** [comment]
Ah! I feared further updates were needed for 1.6.0? But I've checked the sources and indeed they aren't, the newer API versions are a superset of the one I'm using.

**Pull request closed without merging**
